language: python
python:
  - "2.7"
cache: pip
install: []
script: 
  - sudo apt-get install graphviz
  - bash -e "make_encrypt_site.sh"
  - which dot
after_success:
  - bash -e make_encrypt_site.sh
  - bash -e travis_push.sh  
env:
  global:
    GITHUB_PATH: "shouldsee/travis_test"

# deploy:
#   github_token: $GITHUB_TOKEN
#   provider: pages
#   skip_cleanup: true
#   keep_history: true
#   target-branch: gh-pages
#   on:
#     branch: master
