language: python
python:
  - "2.7"
cache: pip
install: []
script: 
  - find . -type l -delete 
  - echo PASS
#  - bash -e make_output.sh
deploy:
  github_token: $GITHUB_TOKEN
  provider: pages
  skip_cleanup: true
  keep_history: true
  target-branch: gh-pages
  on:
    branch: master
