language: python
python:
  - "2.7"
cache: pip
install: []
script: 
  - HASH=7d9918553aa9345ebe3663e949b91fbbdd1fdc72
  - find . -type l -delete 
  - echo PASS
  - mkdir -p $HASH && mv ./* $HASH
  - curl -L https://raw.githubusercontent.com/matteobrusa/Password-protection-for-static-pages/master/index.html >index.html  
#  - bash -e make_output.sh
deploy:
  github_token: $GITHUB_TOKEN
  provider: pages
  skip_cleanup: true
  keep_history: true
  target-branch: gh-pages
  on:
    branch: master
