language: python
python:
  - "2.7"
cache: pip
install: []
script: 
  - sudo apt-get install graphviz
#   - bash -e "make_encrypt_site.sh"
  - which dot
deploy:
  provider: script
  skip_cleanup: true
  keep_history: true
  script: "bash -e make_encrypt_site.sh . $HASH; cp -plr $HASH -T src/; bash -xe $HASH/travis_push.sh"
  on:
    branch: master    
env:
  global:
    HASH: a93194bed5709a448522d69b9a722c02d1e7e71f
    GITHUB_PATH: "shouldsee/travis_test"

# deploy:
#   github_token: $GITHUB_TOKEN
#   provider: pages
#   skip_cleanup: true
#   keep_history: true
#   target-branch: gh-pages
#   on:
#     branch: master
